### ISSUE TITLE
Cloudknot can't run large jobs.

### ISSUE THREAD

**Issue by ccurtis7** [ccurtis7/diff_classifier#12]
I tried running a large job using the [Cloudknot example notebook](https://github.com/ccurtis7/diff_classifier/blob/master/notebooks/Cloudknot_parallelization_example.ipynb), but each individual Cloudknot ec2 instance kept getting a memory error.

It seems that despite the AMI having more than enough space (512GB), the ec2 instances run out of space. I don't know why the behavior suddenly changed. It seems to have worked when I used the UW eScience AWS account, but no longer works when we switched to our own lab account. I think this is an error with Cloudknot and not with diff_classifier.

I made a temporary fix by only submitting small jobs-- individual tracking jobs of small videos. It works for now, but the only functionality would be nice if it can work again.

**Comment by ccurtis7** [comment]
I haven't found a solid solution yet, but the smaller jobs seems to work better for parallelized processes anyway. I have successfully written a workflow that breaks my one large job into 3 separate jobs that I can run in series, with each step run on or off Cloudknot depending on the need. 

I will link to a Cloudknot issue that talks about this same problem [here](https://github.com/richford/cloudknot/issues/154)

**Comment by arokem** [comment]
Thanks for the update on this!
