### ISSUE TITLE
imagej.track tparams arguments don't have defaults

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#20]
If not all keys in `tparams` are passed, a `KeyError` is raised. The code tries to use that key but it can't find it. This means there are functionally no defaults for `tparams`; all keys in `tparams` have to be specified.

Here's the signature for `imagej.track`:

https://github.com/ccurtis7/diff_classifier/blob/738b3f958758a9bcadfeaec1c7f8319e9f532eeb/diff_classifier/imagej.py#L101-L106

I'd imagine the `tparams` argument in `track` is supposed to have defaults for `radius`/etc, especially given the example at https://github.com/ccurtis7/diff_classifier/blob/master/notebooks/diff_classifier_demo.ipynb with the line

``` python
ij.track(filename, outfile, template=None, fiji_bin=None, quality=20.0, xdims=(0, 128), ydims=(0, 128),
         linking_max_distance=15.0, gap_closing_max_distance=15.0, max_frame_gap=5)
``` 

which does not include `tparams` (and if it did, it wouldn't include `radius` or `threshold`).

**Comment by stsievert** [comment]
`tparams` is also a mutable default argument, which raises is a Python gotcha. For more details see https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

**Comment by ccurtis7** [comment]
Thanks for this catch. The demo in diff_classifier_demo.ipynb was running on an older version that I failed to update. I have since fixed the behavior so it should work now.


I have modified the default behavior of `tparams` such that you can specify individual keys manually and retain the original defaults for all other keys. I do like this behavior better, as you shouldn't have a `KeyError` raised.

**Comment by stsievert** [comment]
I think some caution should be taken with setting defaults to be dictionaries. It's easy to get into difficulty with repeated calls to `track`. See https://reinout.vanrees.org/weblog/2012/04/18/default-parameters.html for an example and reasoning too.

I think something like below would avoid the issue of mutable defaults:

``` python
# not recommended
# def foo(d={1: "foo", 2: "bar"}):

# recommended
def foo(d=None):
    d_defaults = {1: "foo", 2: "bar"}
    if d is None:
        d = {}
    for k, v in d_defaults:
        if k not in d:
            d[k] = v
```

**Comment by ccurtis7** [comment]
Thanks, this looks much better. I just modified the defaults to reflect this behavior.
