### ISSUE TITLE
Running demos yields ClientError when downloading data

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#21]
For example, when running https://github.com/ccurtis7/diff_classifier/blob/master/notebooks/averaging_demo.ipynb I run the cell with

``` python-traceback
for _ in [...]:
    aws.download_s3('{}/geomean_{}.csv'.format(folder, sample_name), 'geomean_{}.csv'.format(sample_name), bucket_name=bucket)
```

and wind up with an `ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`. I'm not sure why this is given the bucket name, `nancelab.publicfiles`. Here's the traceback:

``` python
ClientError                               Traceback (most recent call last)
<ipython-input-3-8fe9ed826390> in <module>()
----> 6     aws.download_s3('{}/geomean_{}.csv'.format(folder, sample_name), 'geomean_{}.csv'.format(sample_name), bucket_name=bucket)

~/anaconda3/lib/python3.6/site-packages/diff_classifier/aws.py in download_s3(remote_fname, local_fname, bucket_name)
---> 35         buckt.download_file(remote_fname, local_fname)

~/anaconda3/lib/python3.6/site-packages/boto3/s3/inject.py in bucket_download_file(self, Key, Filename, ExtraArgs, Callback, Config)
--> 246         ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)

~/anaconda3/lib/python3.6/site-packages/boto3/s3/inject.py in download_file(self, Bucket, Key, Filename, ExtraArgs, Callback, Config)
--> 172             extra_args=ExtraArgs, callback=Callback)

~/anaconda3/lib/python3.6/site-packages/boto3/s3/transfer.py in download_file(self, bucket, key, filename, extra_args, callback)
--> 307             future.result()

~/.local/lib/python3.6/site-packages/s3transfer/futures.py in result(self)
---> 73             return self._coordinator.result()

~/.local/lib/python3.6/site-packages/s3transfer/futures.py in result(self)
--> 233             raise self._exception

~/.local/lib/python3.6/site-packages/s3transfer/tasks.py in _main(self, transfer_future, **kwargs)
--> 255             self._submit(transfer_future=transfer_future, **kwargs)

~/.local/lib/python3.6/site-packages/s3transfer/download.py in _submit(self, client, config, osutil, request_executor, io_executor, transfer_future)
--> 349                 **transfer_future.meta.call_args.extra_args

~/anaconda3/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
--> 314             return self._make_api_call(operation_name, kwargs)

~/anaconda3/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
--> 612             raise error_class(parsed_response, operation_name)

ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by stsievert** [comment]
I get this on

* `pca_demo.ipynb`
* `cloudknot_parallelization_demo.ipynb`
* `averaging_demo.ipynb`

**Comment by stsievert** [comment]
I get this error even though my AWS credentials are entered in `~/.aws/credentials` as mentioned [on the boto docs][1] and on the ["example data" documentation page][2].

[1]:https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html#configuration
[2]:https://ccurtis7.github.io/diff_classifier/example_data.html

**Comment by ccurtis7** [comment]
Hmmm, this is odd. Let me check on that bucket. The nancelab.publicfiles repo is read-only last time I checked. That might cause problems on demos downstream.

Could you potentially copy the files to a bucket owned by you, and run all the functions in those buckets instead? I think that's probably the best way to approach it.

**Comment by ccurtis7** [comment]
I just added this to the bucket policy, so I hope you can get the files now?

`{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::nancelab.publicfiles/*"
        }
    ]
}`


I still think it would be best if you copied them to a private repo of your own, as the write functions won't work downstream. I should probably add these instructions into the demos so its clear it won't run as-is.

**Comment by stsievert** [comment]
Thanks for resolving this in https://github.com/ccurtis7/diff_classifier/commit/2228ec9b3f3b51ae046a218f6da944ac627f28ea @ccurtis7. That helped a ton, especially with the relevant S3 documentation: https://aws.amazon.com/premiumsupport/knowledge-center/move-objects-s3-bucket/.

I think I'd like to note that mentions example data on https://ccurtis7.github.io/diff_classifier/example_data.html. That's the place I'd expect it, and would also expect a link to the relevant S3 docs.
