### ISSUE TITLE
No Fiji installation does not raise an error

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#22]
I am testing for if Fiji not installed. When I run `diff_classifier_demo.ipynb`, I run

``` python
>>> # Cell 5
>>> ij.track(filename1, outfile, template=None, fiji_bin=None, tparams=tparams)
... print("Done with tracking.  Should output file of name {}".format(outfile))
/Applications/Fiji.app/Contents/MacOS/ImageJ-macosx --ij2 --headless --run /var/folders/_p/t_mfcz_90vx3shw664l6kpbr0000gq/T/tmp1fr_3dgs.py
Done with tracking.  Should output file of name Traj_FakeTracks.csv

>>> # part of Cell 6
>>> traj = ut.csv_to_pd(outfile)
No data in csv file
```

There is no error raised here. The notebook eventually raises a `ValueError: max() arg is an empty sequence` because no data is in the dataframe.

**Comment by stsievert** [comment]
I think this is fixed by having a hard dependency on `fijibin`. It installs quickly, and after running `pip install fijibin`, I can do

``` python
>>> import fijibin
Fiji missing in /Users/scott/.bin/Fiji-20141125.app
Downloaded 100 percent
Extracting zip
>>> fijibin.FIJI_ROOT
'/Users/scott/.bin/Fiji-20141125.app'
```

This provides a path to an executable, as mentioned on https://ccurtis7.github.io/diff_classifier/getting_started.html. I think this would resolve the issue.

**Comment by ccurtis7** [comment]
So, to fix this I need to:

(1) include `fijibin` in the `setup.py` file and
(2) edit the `track` function to use `fijibin.FIJI_ROOT` to point to the binary, instead of the current semi-manual `fiji_bin` variable.

Would that be enough?

**Comment by stsievert** [comment]
> 1. include fijibin in the setup.py file and
> 2. edit the track function to use fijibin.FIJI_ROOT to point to the binary, instead of the current semi-manual fiji_bin variable.

Yes, that's what I would do. It might be `fijibin.BIN` instead of `fijibin.FIJI_ROOT`.

I'd probably write the code so Fiji is only downloaded when needed and to allow users to use their own Fiji.

**Comment by ccurtis7** [comment]
OK, so I used `fijibin.BIN` like you suggested, and made edits to `setup.py` and `track`. I still use the `fiji_bin` object to reference the binary.

I think it would be best if `fijibin` were able to detect a pre-existing download of fiji, but I can't find any reference to such functionality. As-is, if `fiji_bin` is set to `None`, fiji will be downloaded. If the user wants to use a pre-existing download of fiji, they need to manually reference define the binary in `fiji_bin`.
