### ISSUE TITLE
Python 2/3 compatibility unclear-ish

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#26]
On the homepage it's mentioned:

> The current diff_classifier release behaves a little funky. Most of the code is optimized for Python 3 and isn’t guaranteed to work in Python 2. However, due to some undesirable behavior of the Cloudknot dependency in Python3, any jobs submitted to AWS with a cloudknot.knot object must be done using Python2. In essence, diff_classifier should be run locally using Python3, ec2 instances called upon in AWS Batch should use Python3, but Cloudknot submissions through an IPython notebook should be run using Python2. See example notebooks below for more guidance.

If I'm interpreting this correctly, this means to use Python 3 unless submitting a Cloudknot job. In this case, Python 2 must be run locally to submit a Cloudknot job. However, the Cloudknot job (which launches an AWS Batch) should use Python 3.

Is this interpretation correct? This could be cleaned up a bit I think. I've looked in the example notebooks, but don't see much guidance.

**Comment by stsievert** [comment]
If my interpretation, I'd suggest

> Use Python 3 for almost everything. Unfortunately, Python 2 must be used for one task: launching Cloudknot jobs. This means that Python 2 must be run locally when launching Cloudknot jobs, which launches an AWS Batch. This AWS Batch should use Python 3.

For guidance in the notebooks, it might be useful to have a statement to make sure Python 2 is used to launch CloudKnot jobs:

``` python
import sys
assert sys.version[0] == "2", "Python 2 must be used to launch CloudKnot jobs"
```

**Comment by ccurtis7** [comment]
I added in your recommended language into the docs, and this `assert` system is fantastic. I added them into the cloudknot notebook.
