### ISSUE TITLE
Checking Cloudknot functionality

### ISSUE THREAD

**Issue by ccurtis7** [ccurtis7/diff_classifier#28]
Hey @stsievert, any chance you can take a look at this this weekend?

**Comment by stsievert** [comment]
I put it on today's checklist this morning – I'd like to get this done today. Thanks for the followup.

**Comment by stsievert** [comment]
I ran into some issues with the cloudknot parallelization demo. The issues I ran into:

* copying the S3 files to my bucket took about 15 minutes (20GB at about 20 MiB/s)
* I had issues with the upload/download of the TIFFs in `diff_classifier.cloudknot.split` that took a long time to resolve (crappy wifi, moving to cluster, using cluster disk space optimally).

It'd be nice if this could be reduced (it took me over an hour to resolve), but it's not blocking on the JOSS review. 

---

Also, small nit: it'd be nice if the `bucket` argument of `diff_classifier.knotlets.split` be required. Currently, it defaults to `nancelab.publicfiles` bucket, which I don't have access to write to.

**Comment by stsievert** [comment]
It's nice to have a real-world analysis use case in the Cloudknot demo. I didn't express that in https://github.com/ccurtis7/diff_classifier/issues/28#issuecomment-457394328. I think this demo should remain as is, and it'd be nice to add one that's a little quicker to run.

**Comment by ccurtis7** [comment]
Do you have any recommendations about speeding up both the copying across buckets and downloading from AWS? In the experimental workflow, uploading to AWS is always the bottleneck, but the downloads and transfer seemed fine as long as you were working from an EC2 instance. Overall though, doing the entire analysis in AWS is lightyears faster than what I could do locally.

---

To make the `bucket` argument required, do I just remove the default option?

---

Oh, interesting, were you able to get the entire notebook to run in Python3? I thought it had to do something with the `subprocess` function having different behavior, but I'm not quite sure. @arokem, do you remember why we had to insist on running the Cloudknot submission in Python2? 

As for the buggy behavior of AWS, I know how to navigate around that problem. First, you have to double check that you are in the right region. But even if you are in the right region, it still spend you to the "first time" page sometimes. If you click on "Get started" and then "Skip Wizard", it will take you to the correct interface.

**Comment by arokem** [comment]
Regarding Python 2/3: cloudknot definitely works on both. If I remember correctly, the reason we wanted to work in Python 2 was that we were working on AWS machines that had Python 2.7 installed on them per default and we needed to work under the same environment that root was using to be able to use docker. So I think that this is not a fundamental limitation, but rather a limitation to do with the way we were running this on AWS machines.

**Comment by stsievert** [comment]
> this is not a fundamental limitation, but rather a limitation to do with the way we were running this on AWS machines.

It'd be nice to resolve this. What would be required to change it?

> First, you have to double check that you are in the right region.

Thanks @ccurtis7! I forgot about that annoying limitation. I'll hopefully give this another go soon.

**Comment by arokem** [comment]
On Mon, Jan 28, 2019 at 9:17 AM Scott Sievert <notifications@github.com>
wrote:

> this is not a fundamental limitation, but rather a limitation to do with
> the way we were running this on AWS machines.
>
> It'd be nice to resolve this. What would be required to change it?
>
This is not a problem at all if you are running this on a non-linux system,
where docker doesn't require sudo. For example, I run Cloudknot on my mac
on both Python 2 and Python 3, with different virtualenvs. Alternatively,
you can run your Python process (e.g., Jupyter) as sudo on linux. Either
way, you need to have the permissions to run docker.

Does that make sense?

**Comment by stsievert** [comment]
Why does choice of operating system/sudo privileges enter the picture at all? Is it because sudo will use the `python` command on *nix, which defaults to Python 2.7 on some distros ([PEP 394])? Would this still be an issue if `python` ran Python 3.x?

[PEP 394]:https://www.python.org/dev/peps/pep-0394/

**Comment by arokem** [comment]
On Wed, Jan 30, 2019 at 9:57 AM Scott Sievert <notifications@github.com>
wrote:

> Why does choice of operating system/sudo privileges enter the picture at
> all? Is it because sudo will use the python command on *nix, which
> defaults to Python 2.7 on some distros (PEP 394
> <https://www.python.org/dev/peps/pep-0394/>)? Would this still be an
> issue if python ran Python 3.x?
>
>
Because Cloudknot uses Docker under the hood (and that's an AWS Batch
requirement) and Docker requires sudo priviliges on linux, but not on other
OS (e.g., on the Mac).

**Comment by ccurtis7** [comment]
I went through the notebook and tried running it in Python2 and Python3, and it errors out in Python3 when I run `cloudknot.DockerImage`. It appears that in Python3, there no longer is a `base_image` variable. @arokem and I built a Docker Image that has Fiji properly installed prior to running the code. Interesting that the Python2 and Python3 versions of `cloudknot.DockerImage` have different input variables.

As we have cleaned up the Fiji installation process when using `diff_classifier` perhaps we don't need to use a base image anymore? I'm going to try testing it out.

```

**Comment by ccurtis7** [comment]
Success! I was able to remove the `Python2 requirement` completely after a few modifications. I had to change the call to `cloudknot.DockerImage` in the demo notebook as explained above due to changes in behavior. There was also a new bug in `Trackmate` that made it so the difference of gaussians spot detector was erroring out, resulting in empty CSVs. Weird. I added additional functionality into `imagej.track` that allows the user to choose between difference of gaussians and log of gaussians so you can bypass this error. 

I just need to update the documentation to remove the Python2 requirement, and we're all set. Let me know if you can get the demo notebook running to @stsievert

**Comment by ccurtis7** [comment]
Hey @stsievert, have you been able to check out the updated Cloudknot notebook yet?

**Comment by stsievert** [comment]
I've ran through the notebook tonight, and produced the same plots as the notebook had originally.

**Comment by ccurtis7** [comment]
Great! I'll close this one then.
