### ISSUE TITLE
No Fiji means infinite download loop in diff_classifier_demo.ipynb

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#30]
When executing the cell

``` python
ij.track(filename1, outfile, template=None, fiji_bin=None, tparams=tparams)
print("Done with tracking.  Should output file of name {}".format(outfile))
```

it goes into an infinite download loop. Here's some output when that cell is run from the shell where Jupyter is running:

``` 
fiji-macosx.zip                               100%[==============================================================================================>] 318.48M   876KB/s    in 7m 30s

2019-02-25 19:52:29 (725 KB/s) - 'fiji-macosx.zip' saved [333947759/333947759]

Archive:  fiji-macosx.zip
  inflating: Fiji.app/db.xml.gz
  inflating: Fiji.app/Contents/Info.plist
  ...
  inflating: Fiji.app/java/macosx/adoptopenjdk-8.jdk/jre/Contents/MacOS/libjli.dylib
--2019-02-25 19:52:35--  https://downloads.imagej.net/fiji/latest/fiji-macosx.zip
Resolving downloads.imagej.net... 144.92.48.177
Connecting to downloads.imagej.net|144.92.48.177|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 333947759 (318M) [application/zip]
Saving to: 'fiji-macosx.zip.1'
```

It looks like it unpacked Fiji.app successfully and placed it in `~/Fiji.app`, but it keeps on downloading.

**Comment by stsievert** [comment]
It looks like the environment variable `FIJI_BIN` isn't set in https://github.com/ccurtis7/diff_classifier/blob/66e4fb01592b964b8b80bc09eb6edc0775f3da01/diff_classifier/imagej.py#L68

**Comment by ccurtis7** [comment]
Ah, it's because I send the download to `~/Fiji.app`, but then search for it at `~/Applications/Fiji.app` on a Mac. Sorry about that-- I don't have access to a Mac to test run this. I've been using a Linux.

I did what you recommended and defined the `FIJI_BIN` environment variable after download. Now it should work.

https://github.com/ccurtis7/diff_classifier/blob/master/diff_classifier/imagej.py#L73-83

**Comment by stsievert** [comment]
Thanks – I'll test this later today to verify it works.
