### ISSUE TITLE
Clarification of motivation

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#32]
The motivation:

> Multi-particle tracking software packages abound (see for example this Nature methods paper comparing the results of 14 different teams). But researchers are often on their own when it comes to scale up, analysis, and visualization. Diff_classifier seeks to provide these tools in a centralized package, including MSD and trajectory feature analysis tools, MSD and heatmap plots of output data, and parallelization tools implemented using Amazon Web Services. This package is the primary tool for tracking analysis of nanoparticles in the brain in the Nance research group at the University of Washington.

This is a little unclear – what exactly is "multi-particle tracking"? Why is it hard, and what are the inputs to the process?

It took me a not-short amount of time to realize what the answers to these questions were.

**Comment by stsievert** [comment]
I'd also suggest moving the motivation above usage – why should I use something if I'm not motivated to use it?

**Comment by ccurtis7** [comment]
Thanks @stsievert, I added in some more clarification about MPT and rearranged the motivation section.

**Comment by stsievert** [comment]
> Multi-particle tracking is a powerful tool used in fields as diverse as aeronautics to oceanography that allows researchers to collect spatial information of moving objects from video and image datasets. Multi-particle tracking software packages abound (see for example this Nature methods paper comparing the results of 14 different teams).

But what's an example? I don't care about the name or the fact that it's used all over, at least not right away. How will it help me right now?

Let's say I have a video of a pool table. Would capturing the (x, y) coordinates of each ball be an example of MPT?

**Comment by ccurtis7** [comment]
I included a general description of MPT in the first sentence ('collect spatial information of moving objects from video'). I will throw in a few concrete examples to fill.

**Comment by ccurtis7** [comment]
I added in a number of specific examples from different fields so users have an idea of the use cases for the software.

**Comment by stsievert** [comment]
Thanks for that – it looks much better now!

**Comment by stsievert** [comment]
Could you have make these changes to the JOSS paper too?

**Comment by ccurtis7** [comment]
@stsievert added!
