### ISSUE TITLE
The function assemble_msds assumes a certain format of file names.

### ISSUE THREAD

**Issue by hugopontess** [ccurtis7/diff_classifier#33]
The current form of `assemble_msds` assumes that the filenames have 5 underscores in them. This is inconvenient and results in some incomprehensible error messages when submitting jobs to Cloudknot. Can we find a more efficient method of extracting row and column information from each filename?

**Comment by ccurtis7** [comment]
@hugopontess I fixed assemble_msds so that it doesn't assume a certain format. It calls rows/cols from the end of the prefix names instead of counting from the beginning of the prefix.
