### ISSUE TITLE
The example notebook breaks when boto3 is updated.

### ISSUE THREAD

**Issue by hugopontess** [ccurtis7/diff_classifier#34]
The `my_image` object fails to be created when boto3 is updated, because in attempting to specify `boto3=1.5.28`, it doesn't always completely do this accurately. Fix so that every time the correct version of boto3 is specified.

**Comment by ccurtis7** [comment]
@hugopontess I fixed the demo notebook by changing the way the `my_image` file is modified. It should work regardless of the original boto3 version now.
