### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#37]
[CONTRIBUTING.md][1] clearly mentions how to report issues. However, it does not clearly specify how to contribute features. Some questions it could answer are

* how should the software be tested?
* how should changes be submitted using GitHub's UI?

It'd also be nice to mention "we appreciate feedback" in "Submitting feedback".

[1]:https://github.com/ccurtis7/diff_classifier/blob/facac3f5cf710e1b7ebeebaa09a806c23a67ebd2/CONTRIBUTING.md

**Comment by ccurtis7** [comment]
I added in a few guidelines on contributing new features, and added in the suggested language about feedback. 

Thanks! :)

**Comment by stsievert** [comment]
This might be a good link to include after "please use pull requests": https://scikit-learn.org/dev/developers/contributing.html#how-to-contribute

**Comment by ccurtis7** [comment]
Added the link! Thanks

**Comment by ccurtis7** [comment]
Can I close this @stsievert? Let me know when we're ready to finish up the review process.

**Comment by stsievert** [comment]
Yeah, this can be closed. I think all the bullet points in the review are satisfied, but I'll need to verify.
